"""
MDIE OpenSCAD 3D Engine
Generates parametric OpenSCAD (.scad) code and 3D geometry models
for shafts, keyways, shoulders, bearing seats, and structural machine members.
"""

from typing import Dict, Any, List, Optional
import math
from core.models import EngineeringModel, ShaftSegment

class OpenSCADGenerator:
    @staticmethod
    def generate_scad(
        model: EngineeringModel,
        critical_x: Optional[float] = None,
        highlight_stress: bool = True
    ) -> str:
        """
        Generate clean, parametric, well-commented OpenSCAD source code.
        """
        lines = []
        lines.append("// ====================================================================")
        lines.append(f"// MDIE Generated OpenSCAD Model: {model.name}")
        lines.append(f"// Component: {model.component_type.upper()}")
        lines.append(f"// Total Length: {model.total_length * 1000.0:.1f} mm")
        lines.append(f"// Material: {model.material_id}")
        lines.append("// Generated by Machine Design Intelligence Engine")
        lines.append("// ====================================================================")
        lines.append("")
        lines.append("$fn = 72; // Smooth cylinder tessellation")
        lines.append("")

        # Module parameters
        lines.append("// --- Visual Color Definitions ---")
        lines.append("c_steel = [0.78, 0.82, 0.86, 1.0];")
        lines.append("c_bearing_seat = [0.92, 0.72, 0.28, 1.0];")
        lines.append("c_gear_mount = [0.25, 0.65, 0.85, 1.0];")
        lines.append("c_stress_zone = [0.95, 0.25, 0.20, 0.85];")
        lines.append("c_support = [0.4, 0.4, 0.45, 0.9];")
        lines.append("")

        # Shaft Assembly Module
        lines.append("module machine_shaft() {")
        lines.append("    difference() {")
        lines.append("        // --- Main Stepped Body ---")
        lines.append("        union() {")

        for idx, seg in enumerate(model.segments):
            start_mm = seg.start_pos * 1000.0
            len_mm = (seg.end_pos - seg.start_pos) * 1000.0
            rad_mm = (seg.outer_diameter / 2.0) * 1000.0
            
            # Select color based on feature
            if seg.feature_type == "bearing_seat":
                c_var = "c_bearing_seat"
            elif seg.feature_type in ("gear_mount", "pulley_seat"):
                c_var = "c_gear_mount"
            else:
                c_var = "c_steel"

            lines.append(f"            // Segment {idx+1}: {seg.feature_type} (x={start_mm:.1f} to {start_mm+len_mm:.1f}mm, d={seg.outer_diameter*1000.0:.1f}mm)")
            lines.append(f"            color({c_var})")
            lines.append(f"            translate([{start_mm:.3f}, 0, 0])")
            lines.append(f"            rotate([0, 90, 0])")
            lines.append(f"            cylinder(h={len_mm:.3f}, r={rad_mm:.3f}, center=false);")
            lines.append("")

        lines.append("        }")
        lines.append("")
        lines.append("        // --- Subtractions: Keyways, Bores, and Reliefs ---")

        # Inner bores for hollow segments
        for idx, seg in enumerate(model.segments):
            if seg.inner_diameter > 0:
                start_mm = seg.start_pos * 1000.0
                len_mm = (seg.end_pos - seg.start_pos) * 1000.0
                bore_rad_mm = (seg.inner_diameter / 2.0) * 1000.0
                lines.append(f"        // Inner bore segment {idx+1}")
                lines.append(f"        translate([{start_mm - 0.1:.3f}, 0, 0])")
                lines.append(f"        rotate([0, 90, 0])")
                lines.append(f"        cylinder(h={len_mm + 0.2:.3f}, r={bore_rad_mm:.3f}, center=false);")

        # Keyway slots
        for idx, seg in enumerate(model.segments):
            if seg.keyway:
                kw = seg.keyway
                pos_mm = kw.position * 1000.0
                len_mm = kw.length * 1000.0
                w_mm = kw.width * 1000.0
                d_mm = kw.depth * 1000.0
                shaft_rad_mm = (seg.outer_diameter / 2.0) * 1000.0
                y_offset = shaft_rad_mm - d_mm

                lines.append(f"        // Keyway slot on segment {idx+1} ({kw.standard})")
                lines.append(f"        translate([{pos_mm:.3f}, -{w_mm/2.0:.3f}, {y_offset:.3f}])")
                lines.append(f"        cube([{len_mm:.3f}, {w_mm:.3f}, {d_mm * 2.0:.3f}]);")

        lines.append("    }")
        lines.append("}")
        lines.append("")

        # High Stress Critical Section Callout
        if highlight_stress and critical_x is not None:
            crit_mm = critical_x * 1000.0
            lines.append("module critical_stress_indicator() {")
            lines.append(f"    // Highlight critical stress plane at x = {crit_mm:.1f} mm")
            lines.append("    color(c_stress_zone)")
            lines.append(f"    translate([{crit_mm - 1.5:.3f}, 0, 0])")
            lines.append("    rotate([0, 90, 0])")
            lines.append("    difference() {")
            lines.append("        cylinder(h=3.0, r=40.0, center=false);")
            lines.append("        translate([0, 0, -0.5]) cylinder(h=4.0, r=38.0, center=false);")
            lines.append("    }")
            lines.append("}")
            lines.append("")

        # Supports Visualization
        lines.append("module bearing_supports() {")
        for idx, sup in enumerate(model.supports):
            pos_mm = sup.position * 1000.0
            lines.append(f"    // Bearing support {idx+1} @ x={pos_mm:.1f}mm ({sup.support_type})")
            lines.append("    color(c_support)")
            lines.append(f"    translate([{pos_mm:.3f}, 0, -25])")
            lines.append("    cube([12, 40, 20], center=true);")
        lines.append("}")
        lines.append("")

        # Assembly Call
        lines.append("// --- Render Model ---")
        lines.append("machine_shaft();")
        lines.append("bearing_supports();")
        if highlight_stress and critical_x is not None:
            lines.append("critical_stress_indicator();")

        return "\n".join(lines)

    @staticmethod
    def generate_3d_preview_mesh(model: EngineeringModel) -> Dict[str, Any]:
        """
        Generate lightweight vertex/face/color data for real-time 3D WebGL rendering in browser.
        Returns JSON format directly ingestible by Three.js BufferGeometry.
        """
        cylinders = []
        for seg in model.segments:
            cylinders.append({
                "startX": seg.start_pos * 1000.0,
                "endX": seg.end_pos * 1000.0,
                "length": (seg.end_pos - seg.start_pos) * 1000.0,
                "radius": (seg.outer_diameter / 2.0) * 1000.0,
                "innerRadius": (seg.inner_diameter / 2.0) * 1000.0,
                "feature": seg.feature_type,
                "keyway": {
                    "position": seg.keyway.position * 1000.0,
                    "length": seg.keyway.length * 1000.0,
                    "width": seg.keyway.width * 1000.0,
                    "depth": seg.keyway.depth * 1000.0
                } if seg.keyway else None
            })

        supports = []
        for s in model.supports:
            supports.append({
                "positionX": s.position * 1000.0,
                "name": s.name,
                "type": s.support_type
            })

        loads = []
        for p in model.point_loads:
            loads.append({
                "positionX": p.position * 1000.0,
                "magnitude": p.magnitude,
                "direction": p.direction_deg
            })

        return {
            "name": model.name,
            "totalLengthMm": model.total_length * 1000.0,
            "cylinders": cylinders,
            "supports": supports,
            "loads": loads
        }
